name: swd6_hpp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alsa-lib=1.2.3
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.10.0
  - bleach=4.1.0
  - bokeh=2.4.2
  - boltons=21.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click-completion=0.5.2
  - click-log=0.3.2
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=36.0.0
  - cudatoolkit=11.6.0
  - cudnn=8.2.1.32
  - cupy=10.1.0
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dask-jobqueue=0.7.3
  - dask-mpi=2021.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2021.10.0
  - docutils=0.16
  - eliot=1.14.0
  - eliot-tree=18.1.1
  - entrypoints=0.4
  - executing=0.8.2
  - expat=2.4.6
  - fastrlock=0.8
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.29.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=2022.2.0
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - graphite2=1.3.13
  - graphviz=2.50.0
  - greenlet=1.1.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.4.0
  - heapdict=1.0.1
  - icu=69.1
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=4.11.1
  - importlib-resources=3.3.1
  - importlib_metadata=4.11.1
  - importlib_resources=5.4.0
  - ipykernel=6.9.1
  - ipython=8.0.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - iso8601=1.0.2
  - isort=5.10.1
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jmespath=0.10.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-book=0.12.2
  - jupyter-cache=0.4.3
  - jupyter-server-mathjax=0.2.5
  - jupyter-sphinx=0.3.2
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.2.9
  - jupyterlab_code_formatter=1.4.10
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - jupytext=1.11.5
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - latexcodec=2.0.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm13=13.0.1
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.2
  - librsvg=2.52.5
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libuv=1.43.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - linkify-it-py=1.0.3
  - llvmlite=0.38.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markdown-it-py=1.1.0
  - markupsafe=2.1.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mdit-py-plugins=0.2.8
  - mistune=0.8.4
  - mpi=1.0
  - mpi4py=3.1.3
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - myst-nb=0.13.1
  - myst-parser=0.15.2
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.4.2
  - nbdime=3.1.1
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nodejs=17.4.0
  - notebook=6.4.8
  - nspr=4.32
  - nss=3.74
  - numba=0.55.1
  - numpy=1.21.5
  - openjpeg=2.4.0
  - openmpi=4.1.2
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - pango=1.50.3
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.3
  - pixman=0.40.0
  - platformdirs=2.5.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybtex=0.24.0
  - pybtex-docutils=1.0.1
  - pycparser=2.21
  - pydata-sphinx-theme=0.7.2
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-graphviz=0.19.1
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - readline=8.1
  - requests=2.27.1
  - send2trash=1.8.0
  - setuptools=60.9.3
  - shellingham=1.4.0
  - six=1.16.0
  - smmap=3.0.5
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.4.0
  - sphinx-book-theme=0.1.10
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.0
  - sphinx-external-toc=0.2.3
  - sphinx-jupyterbook-latex=0.4.6
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-panels=0.6.0
  - sphinx-thebe=0.1.1
  - sphinx-togglebutton=0.2.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-bibtex=2.4.1
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlalchemy=1.4.31
  - sqlite=3.37.0
  - stack_data=0.2.0
  - tblib=1.7.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - tree-format=0.1.2
  - typed-ast=1.5.2
  - typing_extensions=4.1.1
  - tzdata=2021e
  - uc-micro-py=1.0.1
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xarray=0.21.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zope.interface=5.4.0
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - algorithms==0.1.4
    - async-timeout==4.0.2
    - black==22.1.0
    - click==8.0.4
    - dask-labextension==5.2.0
    - deprecated==1.2.13
    - filelock==3.6.0
    - flatbuffers==2.0
    - frozenlist==1.3.0
    - grpcio==1.44.0
    - jax==0.3.1
    - jaxlib==0.3.0
    - jupyter-server-proxy==3.2.1
    - jupyterlab-nvdashboard==0.6.0
    - line-profiler==3.4.0
    - multidict==6.0.2
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - pyinstrument==4.1.1
    - pynvml==11.4.1
    - ray==1.10.0
    - redis==4.1.4
    - scipy==1.8.0
    - simpervisor==0.4
    - snakeviz==2.1.1
    - tokenize-rt==4.2.1
    - tomli==2.0.1
    - wrapt==1.13.3
    - yarl==1.7.2
